package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Oct 28, 2007 1:32:02 PM

import net.events.cms.eo.*;
import net.events.cms.pages.*;

import com.webobjects.appserver.*;

import er.directtoweb.*;
import er.extensions.*;

public class CreateDataSetActionBar extends ERDCustomEditComponent {
	
	public DataSetTemplate currentDataSetTemplate;

    public CreateDataSetActionBar(WOContext context) {
        super(context);
    }
    
    public WOComponent createNew () {
    	this.session().takeValueForKey(currentDataSetTemplate, "requestedObject");
    	ERXThreadStorage.takeValueForKey(object(), "CURRENT_PARTICIPANT");
    	EVDataSetPage nextpage = (EVDataSetPage) this.pageWithName(EVDataSetPage.class.getName());
    	nextpage.setNextPage(this.context().page());
    	nextpage.setLastPage(this.context().page());
    	
    	return nextpage;
    }

}