package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Jul 28, 2007 10:22:17 PM

import net.events.cms.eo.*;
import net.events.extensions.*;

import com.webobjects.appserver.*;

/**
 * Displays a blog entry on a blog list page
 * 
 * @author cug
 *
 */
public class EVBlogEntryComponent extends EVComponent {
	
	private BlogEntry blogEntry;
	private Boolean showTeaser;
	private Boolean disableDetailLinks;
	
    public EVBlogEntryComponent(WOContext context) {
        super(context);
    }
    
	/**
	 * @return the blogEntry
	 */
	public BlogEntry blogEntry() {
		return blogEntry;
	}

	/**
	 * @param blogEntry the blogEntry to set
	 */
	public void setBlogEntry(BlogEntry blogEntry) {
		this.blogEntry = blogEntry;
	}

	public void setShowTeaser (Boolean flag) {
		this.showTeaser = flag;
	}
	
	public boolean showTeaser () {
		return this.showTeaser;
	}

	/**
	 * @return the enableDetailLinks
	 */
	public Boolean disableDetailLinks() {
		if (this.disableDetailLinks == null) {
			return Boolean.FALSE;
		}
		return disableDetailLinks;
	}

	/**
	 * @param enableDetailLinks the enableDetailLinks to set
	 */
	public void setDisableDetailLinks(Boolean flag) {
		this.disableDetailLinks = flag;
	}
	
	/**
	 * The current batch
	 * 
	 * @return
	 */
	public Object currentBatch () {
		return this.context().request().formValueForKey("batch");
	}
	
	/**
	 * Disable the link to the detail?
	 * 
	 * @return
	 */
	public boolean disableLink () {
		return this.disableDetailLinks().booleanValue() || blogEntry.content() == null || blogEntry.content().length() == 0;  
	}
	
	/** 
	 * Whether or not to show the "Read more" link
	 * 
	 * @return
	 */
	public boolean showReadMoreLink () {
		return !this.disableLink();
	}
	
	public String catId () {
		return  this.stringValueForBinding("catId");
	}
	
	public void setCatId (String s) {
		this.setValueForBinding(s, "catId");
	}
}