package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Aug 30, 2007 8:41:29 PM

import net.events.cms.eo.*;
import net.events.extensions.*;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

public class EVBlogCategoryList extends EVComponent {
	
	/**
	 * The current page
	 */
	private BlogPage page;
	
	/**
	 * For iterating over the list
	 */
	public BlogEntryCategory currentCategory;

    /**
     * Standard constructor
     * 
     * @param context
     */
    public EVBlogCategoryList(WOContext context) {
        super(context);
    }
    
    /**
     * The categories for this blog
     * 
     * @return
     */
    public NSArray categories () {
    	return this.page().blog().categories();
    }

	/**
	 * @return the page
	 */
	public BlogPage page() {
		return page;
	}

	/**
	 * @param page the page to set
	 */
	public void setPage(BlogPage page) {
		this.page = page;
	}

}