package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Aug 19, 2007 5:19:47 PM

import java.util.*;

import net.events.cms.eo.*;
import net.events.cms.extensions.*;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

public class EVDataSetTextfield extends DataSetAnswerComponent {
	
	public String inputValue;
	
    public EVDataSetTextfield(WOContext context) {
        super(context);
    }
    
    public NSArray currentValues () {
    	DataSetTextItem textItem = (DataSetTextItem) this.value().dataSetItem();
    	if (textItem.predefinedValuesArray() != null && textItem.predefinedValuesArray().count() > 0) {
    		NSMutableArray<String> currentValues = new NSMutableArray<String>();

    		String textValue = ((DataSetTextItemValue) this.value()).textValue();
    		if (textValue != null) currentValues.addObject(textValue);

	    	Enumeration<String> enumeration = textItem.predefinedValuesArray().objectEnumerator();
	    	while (enumeration.hasMoreElements() && currentValues.count() < 10) {
	    		String currentValue = enumeration.nextElement();
	    		if (textValue == null || currentValue.toLowerCase().startsWith(textValue.toLowerCase())) {
	    			currentValues.addObject(currentValue);
	    		}
	    	}
	    	return currentValues;
    	}
    	else return null;
    }

}