package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Sep 9, 2007 10:07:07 PM

import net.events.cms.extensions.*;

import com.webobjects.appserver.*;

public class EVDataSetNumberField extends DataSetAnswerComponent {

    public EVDataSetNumberField(WOContext context) {
        super(context);
    }

}