package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Oct 3, 2007 10:45:11 PM

import net.events.cms.extensions.*;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

public class EVDataSetDatefield extends DataSetAnswerComponent {

    public EVDataSetDatefield(WOContext context) {
        super(context);
    }

    public NSTimestamp now () {
    	return new NSTimestamp();
    }
}