package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Sep 9, 2007 10:07:32 PM

import net.events.cms.extensions.*;

import com.webobjects.appserver.*;

public class EVDataSetDecimalField extends DataSetAnswerComponent {

    public EVDataSetDecimalField(WOContext context) {
        super(context);
    }

}