package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at 13.02.2007 23:09:41

import net.events.cms.eo.*;

import com.webobjects.appserver.*;
import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;

import er.extensions.*;

/**
 * Componoent class for PageWrappers
 * 
 * @author cug
 */
public class EVPageWrapper extends ERXInlineTemplate {
	
    /**
     * Standard constructor
     * 
     * @param context
     */
    public EVPageWrapper(WOContext context) {
        super(context);
    	if (this.context().page() != null) {
    		try {
    			String pageName = (String) this.context().page().valueForKeyPath("pageTitle");
    			this.dynamicBindings().takeValueForKey(pageName, "pageTitle");
    		}
    		catch (Exception e) {
				// TODO: handle exception
			}
    	}
    	else this.dynamicBindings().takeValueForKey("event-s Designer", "pageTitle");
    }

    public void appendToResponse (WOResponse r, WOContext c) {
    	super.appendToResponse(r, c);
    }

}