package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Jul 30, 2007 9:28:33 AM

import net.events.cms.eo.*;
import net.events.extensions.*;

import com.webobjects.appserver.*;

public class EVRecentBlogEntriesComponent extends EVComponent {
	
	private AbstractPage page;

    public EVRecentBlogEntriesComponent(WOContext context) {
        super(context);
    }

	/**
	 * @return the page
	 */
	public AbstractPage getPage() {
		return page;
	}

	/**
	 * @param page the page to set
	 */
	public void setPage(AbstractPage page) {
		this.page = page;
	}
	
}