package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Sep 8, 2007 11:29:04 PM

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

import er.extensions.*;

public class EVToOneRelationship extends ERXToOneRelationship {

    public EVToOneRelationship(WOContext context) {
        super(context);
    }
    
    public NSArray theList() {
        if (_list==null) {
            _list = super.theList();
            if (!isMandatory() && this.isRadio()) {
                NSMutableArray array = _list.mutableClone();
                if (array != null && array.count() > 1 && array.objectAtIndex(0).equals(NO_SELECTION_STRING)) {
	                array.removeObjectAtIndex(0);
	                _list = array;
                }
            }
            
        }
        return _list;
    }

}