package net.events.cms.pages;
// Generated by the WOLips Templateengine Plug-in at Jun 2, 2007 8:34:14 PM

import net.events.cms.extensions.*;

import com.webobjects.appserver.*;

public class EVHtmlPage extends EVCMSPage {

    /**
     * Simple HTML page. Takes HTML content from the database and uses the supplied PageWrapper. 
     * 
     * @param context
     */
    public EVHtmlPage(WOContext context) {
        super(context);
    }
    
 }