package net.events.d2w.extensions;
// Generated by the WOLips Templateengine Plug-in at Apr 1, 2007 11:04:02 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERD2WDisplayString;

public class EVD2WDisplayLocalizedString extends ERD2WDisplayString {

    public EVD2WDisplayLocalizedString(WOContext context) {
        super(context);
    }

}