package net.events.cms.pages;
// Generated by the WOLips Templateengine Plug-in at Sep 5, 2007 5:30:37 PM

import net.events.cms.extensions.*;

import com.webobjects.appserver.*;

public class EVBlogCommentPage extends EVCMSPage {

    public EVBlogCommentPage(WOContext context) {
        super(context);
    }

}