package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Apr 18, 2007 9:22:04 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERDQueryPageRepetition;

public class EVD2WQueryPageRepetition extends ERDQueryPageRepetition {

    public EVD2WQueryPageRepetition(WOContext context) {
        super(context);
    }

}