package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Oct 27, 2007 6:14:14 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.relationships.ERD2WEditToOneRelationship;

public class EVD2WGroupingEditToOne extends ERD2WEditToOneRelationship {

    public EVD2WGroupingEditToOne(WOContext context) {
        super(context);
    }

}