package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Aug 15, 2007 9:46:19 AM

import net.events.d2w.extensions.EVD2WApplication;

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;

import er.directtoweb.ERDEditToManyRelationship;
import er.extensions.ERXArrayUtilities;

public class EVD2WEditToManyRelationship extends ERDEditToManyRelationship {

    private String updateContainerId;

	public EVD2WEditToManyRelationship(WOContext context) {
        super(context);
    }

    public String updateContainerId () {
    	if (this.updateContainerId == null) {
    		this.updateContainerId = this.getClass().getSimpleName() + ((EVD2WApplication)this.application()).randomInteger();
    	}
    	return this.updateContainerId;
    }
    
    public String innerContainerId () {
    	return this.updateContainerId + "_" + index;
    }
    
    public WOComponent deleteCurrent() {
    	super.deleteObject(currentObject);
    	return null;
    }
    
    /**
     * Returns the objects sorted, if there is a sort key given
     */
    public NSArray objects () {
    	if (this.d2wContext().valueForKey("sortKey") != null) {
    		return ERXArrayUtilities.sortedArraySortedWithKey(super.objects(), (String) this.d2wContext().valueForKey("sortKey")).immutableClone();
    	}
    	else return super.objects();
    }
    
}