package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Mar 3, 2007 10:02:21 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERDDeleteButton;
import er.extensions.ERXValueUtilities;

public class EVD2WDeleteButton extends ERDDeleteButton {

    public EVD2WDeleteButton(WOContext context) {
        super(context);
    }
    
    public boolean useTextLink () {
    	return ERXValueUtilities.booleanValueWithDefault(d2wContext().valueForKey("textLink") , false);
    }

}