package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Oct 26, 2007 8:35:42 PM

import org.apache.log4j.Logger;

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.bool.ERD2WCustomQueryBoolean;

/**
 * Only subclassed "ERD2WCustomQueryBoolean" for style reasons
 * 
 * @author cug
 */
public class EVD2WQueryBoolean extends ERD2WCustomQueryBoolean {
	
	private Logger log = Logger.getLogger(EVD2WQueryBoolean.class);
	
    public EVD2WQueryBoolean(WOContext context) {
        super(context);
    }
    
    
}