package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Jun 27, 2007 10:55:59 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.ERDActionBar;

public class EVD2WListActionBar extends ERDActionBar {

    public EVD2WListActionBar(WOContext context) {
        super(context);
    }

}