package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Apr 21, 2007 11:43:51 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.EditPageInterface;

import er.directtoweb.ERDEmptyListMessage;
import er.extensions.ERXGenericRecord;

public class EVD2WEmptyListMessage extends ERDEmptyListMessage {

    public EVD2WEmptyListMessage(WOContext context) {
        super(context);
    }

	/* (non-Javadoc)
	 * @see er.directtoweb.ERDEmptyListMessage#createObject()
	 */
	@Override
	public WOComponent createObject() {
		Object nextpage = super.createObject();

		if (nextpage instanceof EditPageInterface) {
			try {
				if (this.context().page() != null && this.context().page().valueForKey("object") != null) {
					ERXGenericRecord nextObject = (ERXGenericRecord) ((WOComponent) nextpage).valueForKey ("object");
					ERXGenericRecord thisObject = (ERXGenericRecord) this.context().page().valueForKey("object");
					
					String relationshipName = (String)this.d2wContext().valueForKey("reverseRelationshipKey");
					nextObject.addObjectToBothSidesOfRelationshipWithKey(
							thisObject.localInstanceIn(nextObject.editingContext()), 
							relationshipName);
				}
			}
			catch (Exception e) {
			}
		}
		
		return (WOComponent) nextpage;
	}
    
    
}