package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Mar 3, 2007 9:52:20 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.buttons.ERDInspectButton;
import er.extensions.foundation.ERXValueUtilities;

public class EVD2WInspectButton extends ERDInspectButton {

    public EVD2WInspectButton(WOContext context) {
        super(context);
    }
    
    public boolean useTextLink () {
    	return ERXValueUtilities.booleanValueWithDefault(d2wContext().valueForKey("textLink") , false);
    }

}