package net.events.d2w.components;

import org.apache.log4j.Logger;

import com.webobjects.appserver.WOContext;
import com.webobjects.foundation.NSArray;

import er.directtoweb.components.ERD2WStatelessComponent;

// Generated by the WOLips Templateengine Plug-in at Apr 27, 2008 12:18:17 AM
public class EVD2WPropertySpan extends ERD2WStatelessComponent {
	
	private static Logger log = Logger.getLogger(EVD2WPropertySpan.class);
	
    public EVD2WPropertySpan(WOContext context) {
        super(context);
    }
    
    public void reset () {
    	super.reset();
    }

	public String cssClass() {
		if (this.hasNoErrors()) {
			return (String) d2wContext().valueForKey("classNameForPropertyValue");
		}
		else {
			return (String) d2wContext().valueForKey("classNameForPropertyValueWithValidationError");
		}
	}
	
    public boolean hasNoErrors() {
        if(false) {
            String keyPath = "errorMessages." + displayNameForProperty();
            return d2wContext().valueForKeyPath(keyPath) == null;
        }
        return !validationExceptionOccurredForPropertyKey();
    }
    
    public boolean validationExceptionOccurredForPropertyKey() {
        if (d2wContext().propertyKey() == null) {
            return false;
        } else {
            String propertyKey = d2wContext().propertyKey();
            boolean contains = keyPathsWithValidationExceptions().containsObject(propertyKey);
            if (log.isDebugEnabled())
            	log.debug("propertyKey="+propertyKey+", keyPathsWithValidationExceptions="+keyPathsWithValidationExceptions());
            return contains;
        }
    }
    
    public NSArray keyPathsWithValidationExceptions() {
        NSArray exceptions = (NSArray)d2wContext().valueForKey("keyPathsWithValidationExceptions");
        return exceptions != null ? exceptions : NSArray.EmptyArray;
    }
}