package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Mar 3, 2007 11:00:00 AM

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.ERDBannerComponent;

public class EVD2WBannerComponent extends ERDBannerComponent {

    public EVD2WBannerComponent(WOContext context) {
        super(context);
    }

}