package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Mar 3, 2007 9:04:32 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERDEditButton;
import er.extensions.ERXValueUtilities;

public class EVD2WEditButton extends ERDEditButton {

    public EVD2WEditButton(WOContext context) {
        super(context);
    }
    
    public boolean useTextLink () {
    	return ERXValueUtilities.booleanValueWithDefault(d2wContext().valueForKey("textLink") , false);
    }
    
    public String imageFileName () {
    	return "write-btn.gif";
    }

}