package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at 18.02.2007 21:36:36

import com.webobjects.appserver.WOContext;

import er.extensions.ERXErrorDictionaryPanel;

public class EVD2WErrorDictionaryPanel extends ERXErrorDictionaryPanel {

    public EVD2WErrorDictionaryPanel(WOContext context) {
        super(context);
    }
    
    public String errorTitleMessage () {
    	if (this.errorMessages() != null && this.errorMessages().allKeys().count() > 1) {
    		return "There are errors in the form below. Please correct them.";
    	}
    	else {
    		return "Please correct the error in the form below!";
    	}
    }

}