package net.events.designer.components;
// Generated by the WOLips Templateengine Plug-in at Aug 3, 2007 3:14:34 PM

import net.events.cms.extensions.*;
import net.events.extensions.*;

import com.webobjects.appserver.*;
import com.webobjects.eoaccess.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.*;

import er.extensions.*;

public class AdminOverviewPage extends EVComponent {
	
	private EOEditingContext editingContext;

    public AdminOverviewPage(WOContext context) {
        super(context);
        
        this.editingContext = ERXEC.newEditingContext();
    }
    
    public void awake () {
    	super.awake();
    }
    
    public void appendToResponse (WOResponse r, WOContext c) {
    	super.appendToResponse(r, c);
    }

	/**
	 * @return the currentUsers
	 */
	public NSArray currentUsers() {
		String sql = EVCMSQueryManager.loggedInUsersWithNavigationState();
		return EOUtilities.rawRowsForSQL(editingContext, "EVCMS", sql, null);
	}

}