package net.events.designer.components;
// Generated by the WOLips Templateengine Plug-in at Feb 20, 2007 1:02:51 AM

import net.events.designer.appserver.*;

import com.webobjects.appserver.*;
import com.webobjects.foundation.*;

import er.extensions.*;

/**
 * The footer part of admin pages
 * 
 * @author cug
 *
 */
public class PageFooter extends WOComponent {

    /**
     * Standard constructor
     * @param context
     */
    public PageFooter(WOContext context) {
        super(context);
    }
    
    public WOComponent showLoggedInUsers() {
    	ERXNavigationManager.manager().navigationStateForSession(this.session()).setState(new NSArray<Object>(new Object[] { "Admin", "LoggedInUsers" }));
    	return this.pageWithName(AdminOverviewPage.class.getName());
    }
    
    public boolean showUserCount () {
    	if (((Session) session()).currentUser().isSuperAdmin() && this.context().page().name() != AdminOverviewPage.class.getName()) {
    		return true;
    	}
    	else return false;
    }
}