package net.events.d2w.pages;
// Generated by the WOLips Templateengine Plug-in at Aug 7, 2007 4:34:36 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class EVGenericErrorPage extends WOComponent {

    public EVGenericErrorPage(WOContext context) {
        super(context);
    }

}