package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Mar 2, 2007 11:51:21 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERD2WPropertyName;

public class EVD2WListPropertyName extends ERD2WPropertyName {

    public EVD2WListPropertyName(WOContext context) {
        super(context);
    }

}