package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Apr 6, 2007 4:19:05 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.repetitions.ERDInspectPageRepetition;
import er.extensions.foundation.ERXValueUtilities;

/**
 * Cleaned up component, better HTML, more CSS
 * 
 * @author cug
 *
 */
public class EVD2WInspectPageRepetition extends ERDInspectPageRepetition {
	
	/**
	 * Standard constructor 
	 * @param context
	 */
	public EVD2WInspectPageRepetition(WOContext context) {
        super(context);
    }
    
    /**
     * Gets the cellwidth from the d2wContext or calculates it from the maxColumns information for the table
     * 
     * @return
     */
    public String cellWidth () {
    	String width = null;
    	
    	if (this.d2wContext().valueForKey("cellWidth") != null) {
    		width = (String) this.d2wContext().valueForKey("cellWidth");
    	}
    	else {
    		if (this.d2wContext().valueForKey("maxColumns") != null) {
    			int maxColumns = ERXValueUtilities.intValue(this.d2wContext().valueForKey("maxColumns"));
    			width = 100 / maxColumns + "%";
    		}
    		else {
    			width = "50%";
    		}
    	}
    	
    	return width;
    }

}