package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Mar 2, 2007 10:48:08 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2W;
import com.webobjects.directtoweb.InspectPageInterface;
import com.webobjects.eocontrol.EOEnterpriseObject;
import com.webobjects.eocontrol.EOGenericRecord;

import er.directtoweb.ERDListPageRepetition;
import er.extensions.ERXValueUtilities;

public class EVD2WListPageRepetition extends ERDListPageRepetition {
	
	/** 
	 * Used for altenating row colors
	 */
	private boolean rowFlip = false;

	/**
	 * Standard constructor
	 * @param context
	 */
	public EVD2WListPageRepetition(WOContext context) {
        super(context);
    }
	
	/**
	 * Overwritten to support alternating row colors
	 * 
	 * @see er.directtoweb.ERDAttributeRepetition#awake()
	 */
	public void awake () {
		super.awake();
		rowFlip = false;
	}

	/**
	 * row class, used for displaying alternating rows
	 * 
	 * @return
	 */
	public String rowClass () {
		rowFlip = !rowFlip;
		if (this.d2wContext().valueForKey("cssClassForRow") == null) { 
			if (rowFlip) {
				return "d2w_listrow_odd";
			}
			else {
				return "d2w_listrow_even";
			}
		}
		else {
			return (String) this.d2wContext().valueForKey("cssClassForRow");
		}
	}
	
	/**
	 * Return whether this property is sortable
	 * @return
	 */
	public boolean propertyIsSortable () {
		if (ERXValueUtilities.booleanValue(this.d2wContext().valueForKey("propertyIsSortable"))) {
			return false;
		}
		else return true;
	}
	
	public WOComponent inspectObject () {
		InspectPageInterface nextpage = (InspectPageInterface) D2W.factory().inspectPageForEntityNamed(((EOGenericRecord) this.d2wContext().valueForKey("object")).entityName(), session());
		nextpage.setObject((EOEnterpriseObject) this.d2wContext().valueForKey("object"));
		nextpage.setNextPage(this.context().page());
		return (WOComponent) nextpage;
	}
	
	public boolean disableInspectObjectLink () {
		return !ERXValueUtilities.booleanValue(this.d2wContext().valueForKey("enableInspectLink"));
	}
	
}