package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Apr 14, 2007 11:22:29 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.ERDSectionText;

public class EVD2WSectionText extends ERDSectionText {

    public EVD2WSectionText(WOContext context) {
        super(context);
    }

}