package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Oct 21, 2007 9:34:23 PM

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.directtoweb.D2W;
import com.webobjects.directtoweb.InspectPageInterface;
import com.webobjects.eocontrol.EOEnterpriseObject;
import com.webobjects.eocontrol.EOGenericRecord;

import er.directtoweb.components.repetitions.ERDGroupingListPageRepetition;
import er.extensions.foundation.ERXValueUtilities;

public class EVD2WGroupingListPageRepetition extends ERDGroupingListPageRepetition {
	
    public EVD2WGroupingListPageRepetition(WOContext context) {
        super(context);
    }

	public WOComponent inspectObject () {
		InspectPageInterface nextpage = (InspectPageInterface) D2W.factory().inspectPageForEntityNamed(((EOGenericRecord) this.d2wContext().valueForKey("object")).entityName(), session());
		nextpage.setObject((EOEnterpriseObject) this.d2wContext().valueForKey("object"));
		nextpage.setNextPage(this.context().page());
		return (WOComponent) nextpage;
	}

	public boolean disableInspectObjectLink () {
		return !ERXValueUtilities.booleanValue(this.d2wContext().valueForKey("enableInspectLink"));
	}

}