package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Apr 21, 2007 2:19:32 PM

import com.webobjects.appserver.WOContext;

import er.directtoweb.components.strings.ERD2WQueryStringOperator;

public class EVD2WQueryStringOperator extends ERD2WQueryStringOperator {

    public EVD2WQueryStringOperator(WOContext context) {
        super(context);
    }

    public boolean showPopup () {
    	if (this.allQualifierOperators() != null && this.allQualifierOperators().count() > 1) {
    		return true;
    	}
    	else return false;
    }
}