package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Oct 27, 2007 6:08:29 PM

import com.webobjects.appserver.WOContext;
import com.webobjects.eocontrol.EOCustomObject;
import com.webobjects.eocontrol.EOGenericRecord;
import com.webobjects.foundation.NSKeyValueCoding;

import er.extensions.components.ERXToOneRelationship;

public class EVGroupingEditToOne extends ERXToOneRelationship {

    public EVGroupingEditToOne(WOContext context) {
        super(context);
    }
    
    public Object groupObject () {
    	@SuppressWarnings("unused")
		Object key = this.valueForBinding("group");
    	if (this.theCurrentItem() instanceof NSKeyValueCoding) {
    		return ((NSKeyValueCoding) this.theCurrentItem()).valueForKey(this.valueForBinding("group").toString());
    	}
    	else return "";
    }
    
    public String label () {
    	String label;
    	Object object = this.theCurrentItem();
    	if (object instanceof EOGenericRecord) {
    		EOGenericRecord o = (EOGenericRecord) object;
    		Object groupingObject = (NSKeyValueCoding) o.valueForKey(this.stringValueForBinding("group"));
    		label = ((EOCustomObject) groupingObject).userPresentableDescription();
    	}
    	else {
    		label = "";
    	}
    	return label;
    }
    
}