package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at 19.02.2007 00:55:59

import com.webobjects.appserver.WOContext;

import er.extensions.ERXNavigationMenu;

public class EVNavigationTop extends ERXNavigationMenu {

    public EVNavigationTop(WOContext context) {
        super(context);
    }

}