package net.events.d2w.components;
// Generated by the WOLips Templateengine Plug-in at Apr 21, 2007 10:45:49 PM

import com.webobjects.appserver.WOContext;

import er.extensions.ERXNavigationMenu;

public class EVNavigationLeft extends ERXNavigationMenu {

    public EVNavigationLeft(WOContext context) {
        super(context);
    }

}