package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Sep 11, 2007 7:54:11 PM

import net.events.cms.eo.*;
import net.events.extensions.*;

import com.webobjects.appserver.*;

public class EVBlogCommentComponent extends EVComponent {
	
	// used for the repetition
	public BlogComment currentComment;
	
    public EVBlogCommentComponent(WOContext context) {
        super(context);
    }

    public boolean synchronizesVariablesWithBindings() {
    	return false;
    }
}