package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at Sep 3, 2007 3:52:22 PM

import com.webobjects.appserver.*;

public class EVGoogleAdSenseComponent extends WOComponent {

    public EVGoogleAdSenseComponent(WOContext context) {
        super(context);
    }

}