package net.events.cms.components;
// Generated by the WOLips Templateengine Plug-in at 13.02.2007 23:08:48

import net.events.cms.eo.*;
import net.events.cms.extensions.*;
import net.events.extensions.*;

import com.webobjects.appserver.*;

import er.extensions.*;

/**
 * Navigation component for pages with standard Look & Feel
 * 
 * @author cug
 */
public class EVNavigation extends EVComponent {
	
	private AbstractPage page;
	
    /**
     * Standard constructor
     * 
     * @param context
     */
    public EVNavigation(WOContext context) {
        super(context);
    }
    
    /** 
     * Only gets the current page.
     */
    public void awake () {
    	this.page = (AbstractPage) ERXThreadStorage.valueForKey(EVCMSConstants.PAGE_OBJECT_KEY);
    }

	/**
	 * @return the page
	 */
	public AbstractPage page() {
		return page;
	}

	/**
	 * @param page the page to set
	 */
	public void setPage(AbstractPage page) {
		this.page = page;
	}
    
    

}