package net.events.designer.appserver;
// Generated by the WOLips Templateengine Plug-in at 11.02.2007 19:25:05

import net.events.designer.components.*;

import com.webobjects.appserver.*;

import er.extensions.*;

public class DirectAction extends ERXDirectAction {

    /**
     * Standard constructor
     * 
     * @param aRequest
     */
    public DirectAction(WORequest aRequest) {
        super(aRequest);
    }

    /**
     * Returns the login page
     */
    public WOActionResults defaultAction() {
        return pageWithName(Main.class.getName());
    }

}