package net.events.designer.components;

import com.webobjects.appserver.*;

// Generated by the WOLips Templateengine Plug-in at Nov 19, 2007 1:28:05 PM
public class SessionTimeoutPage extends com.webobjects.appserver.WOComponent {
    public SessionTimeoutPage(WOContext context) {
        super(context);
    }
}